inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: around

Layout/IndentationConsistency:
  EnforcedStyle: normal

Layout/LineLength:
  Max: 120

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_special
  Exclude:
    - 'db/**/*'

Layout/ClassStructure:
  Categories:
    module_inclusions:
      - include
      - prepend
      - extend
    associations:
      - belongs_to
      - has_one
      - has_many
    validations:
      - validates
      - validate
    attribute_macros:
      - attr_accessor
      - attr_reader
      - attr_writer

  ExpectedOrder:
    - module_inclusions
    - constants
    - associations
    - validations
    - public_delegate
    - public_attribute_macros
    - public_class_methods
    - initializer
    - public_methods
    - protected_attribute_macros
    - protected_methods
    - private_attribute_macros
    - private_delegate
    - private_methods
